

// Archivos de cabecera - BD
#include "fncBD_DeshacerConexionDB.h"
#include "fncBD_VerificarCuenta.h"
#include "fncBD_ObtenerRegistroDB.h"
#include "fncBD_MostrarConexionDB.h"
#include "fncBD_EstablecerConexionBD.h"
#include "fncBD_ObtenerDatosUser.h"
#include "fncBD_ObtenerDatosBanco.h"
#include "fncBD_MostrarDatosBanco.h"
#include "fncBD_MostrarDatosUser.h"
#include "fncBD_ActualizarDBBanco.h"
#include "fncBD_ActualizarDBUser.h"
#include "fncBD_RegistrarActividad.h"
#include "fncBD_MostrarActividades.h"
#include "fncBD_CrearBDActividades.h"
#include "fncBD_CrearBDBanco.h"
#include "fncBD_CrearBDUsuario.h"
#include "fncBD_RegistrarUsuarioBD.h"
#include "./fncBD_ActualizarUsuariosBD.h"